version: '3.9'

services:
  app:
    build: .
    container_name: stakeaway_gin_api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_TYPE=in-memory
    restart: always
